'use client'

// app/globals.css or _app.tsx
import 'video.js/dist/video-js.css';

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Analytics } from '@vercel/analytics/react'
import { usePathname, useRouter } from "next/navigation";
import { SessionProvider, signOut } from "next-auth/react";
import { useDetectAdBlock  } from "adblock-detect-react";
import { useEffect, ReactNode } from "react";
import Script from "next/script";
import * as gtag from "@/app/lib/gtag";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();

  const isAdBlockDetected = useDetectAdBlock();

  useEffect(() => {
    if (isAdBlockDetected) {
      // Example actions when adblock detected
      // signOut();  // Sign out user if they are logged in
      // router.push('/lmacm/ad-blocker-warning');
    }
  }, [isAdBlockDetected]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      gtag.pageview(pathname);
    }
  }, [pathname]);

  // Optional: prevent render if adblock detected
  // if (isAdBlockDetected) {
  //   return null;
  // }
  return (
    <html lang="en">
      <head>
        <title>Legion Maria Stream | Your Spiritual Media Gallery</title>

        <meta httpEquiv="Delegate-CH" content="Sec-CH-UA https://s.magsrv.com; Sec-CH-UA-Mobile https://s.magsrv.com; Sec-CH-UA-Arch https://s.magsrv.com; Sec-CH-UA-Model https://s.magsrv.com; Sec-CH-UA-Platform https://s.magsrv.com; Sec-CH-UA-Platform-Version https://s.magsrv.com; Sec-CH-UA-Bitness https://s.magsrv.com; Sec-CH-UA-Full-Version-List https://s.magsrv.com; Sec-CH-UA-Full-Version https://s.magsrv.com;"></meta>

        <meta name="6a97888e-site-verification" content="c846d18e475445846be7ef3db6045e68"></meta>

        <meta
          name="description"
          content="Play Game of Numbers for free and win real money by selecting the right number. No deposit required. Withdraw via PayPal once you reach $5."
        />
        <meta
          name="keywords"
          content="game of numbers, win money, number guessing game, free to play, PayPal withdrawal, make money online, Make money easily online, Online money-making website, Earn money from playing games, How to make money without investment, Passive income website"
        />
        <meta name="author" content="Game of Numbers" />
        <meta property="og:title" content="Game of Numbers | Win Real Money" />
        <meta
          property="og:description"
          content="Join the Game of Numbers and win real cash by selecting the right number. Absolutely free to play."
        />
        <meta property="og:image" content="/logo.png" />
        <meta property="og:url" content="https://gameofnumbers.tech" />
        <link rel="canonical" href="https://gameofnumbers.tech" />

        {/* Viewport & Favicon */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* Google Analytics */}
        <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${gtag.GA_TRACKING_ID}`}
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${gtag.GA_TRACKING_ID}', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
        {/* <Script type='text/javascript' src='//pl26127580.profitableratecpm.com/4a/d1/2a/4ad12a6ab63f6e571b51483e9aafefb1.js'></Script> */}
      </head>


      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="ad-banner"></div>

        {/* <Script async type="application/javascript" src="https://a.magsrv.com/ad-provider.js"></Script>
        <ins className="eas6a97888e2" data-zoneid="5663320"></ins>
        <Script id="ad-provider-init" strategy="afterInteractive">
          {`(AdProvider = window.AdProvider || []).push({"serve": {}});`}
        </Script> */}

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SessionProvider
            session={undefined}
            refetchInterval={0}
            refetchOnWindowFocus={false}
          >
            {children}
          </SessionProvider>

          <Toaster
            position="top-center"
            toastOptions={{
              success: {
                style: { background: '#22c55e', color: 'white' },
                iconTheme: { primary: 'white', secondary: '#22c55e' },
              },
              error: {
                style: { background: '#ef4444', color: 'white' },
                iconTheme: { primary: 'white', secondary: '#ef4444' },
              },
            }}
          />

          <Analytics />
        </ThemeProvider>
        {/* <Script type='text/javascript' src='//pl26127543.profitableratecpm.com/b9/eb/f3/b9ebf3ad347ae3d6475d2647154ddd39.js'></Script> */}
      </body>
    </html>
  );
}
